#! /bin/sh
a
pgrep -x sxhkd > /dev/null || sxhkd &


if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
	xrandr --output eDP --mode 1920x1200 --rotate normal --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --left-of eDP --rate 180
	bspc monitor eDP -d VI VII VIII IX X
	bspc monitor HDMI-A-0 -d I II III IV V
fi

if [[ $(xrandr -q | grep 'HDMI-A-0 disconnected') ]]; then
	bspc monitor eDP -d I II III IV V VI VII VIII IX X
fi

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#bspc monitor eDP -d I II III IV V
#bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false 
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
bspc rule -a '*:*:Tor Browser' state=floating rectangle=1000x2000
bspc rule -a mpv state=pseudo_tiled

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &

# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
#picom &
# picom -b &
# Network Applet
nm-applet --indicator &

# easy effects
easyeffects --gapplication-service &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# fcitx
fcitx -dr &

torrents
qbittorrent --no-splash &
nicotine -s &

# colors
bash /home/toytoi/.config/bspwm/bspwm_colors.sh &
